spring:
  application:
    name: newsapp
  profiles:
    active: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhatthcs940@gmail.com
    password: htavdtquyegafxci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  # THÊM CÀI ĐẶT DATABASE VÀO ĐÂY
  datasource:
    url: jdbc:postgresql://localhost:5432/newsapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
google:
  client-id: 307674059153-9djp3m9qqief5t5q9reslqoddeo4abls.apps.googleusercontent.com
server:
  port: 8080

logging:
  level:
    org.springframework: INFO
  'org.springframework.security': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized